INSERT INTO produtos_patrimonio (nome, descricao, numero_identificacao, observacoes, categoria_decoracao, ativo) VALUES
('Notebook 149', 'Necessita de manutenção preventiva.', '50398', 'Localizado no escritório principal.', 17, 0),
('Impressora 518', 'Em ótimo estado, pouco utilizado.', '13460', 'Disponível na sala de reuniões.', 22, 1),
('Televisão 824', 'Novo, ainda em período de garantia.', '77271', 'Sob responsabilidade do setor de manutenção.', 18, 1),
('Armário 557', 'Em ótimo estado, pouco utilizado.', '30980', 'Localizado no escritório principal.', 18, 1),
('Cadeira 840', 'Necessita de manutenção preventiva.', '11453', 'Sob responsabilidade do setor de manutenção.', 20, 1),
('Computador 501', 'Item essencial para o funcionamento do setor.', '79042', 'Sob responsabilidade do setor de manutenção.', 20, 1),
('Computador 704', 'Equipamento em bom estado de conservação.', '47975', 'Sob responsabilidade do setor de manutenção.', 21, 0),
('Notebook 133', 'Necessita de manutenção preventiva.', '31116', 'Inventariado no último balanço patrimonial.', 17, 0),
('Armário 402', 'Novo, ainda em período de garantia.', '88904', 'Disponível na sala de reuniões.', 21, 1),
('Mesa 135', 'Utilizado em treinamentos e reuniões.', '25463', 'Inventariado no último balanço patrimonial.', 22, 0),
('Cafeteira 410', 'Equipamento em bom estado de conservação.', '33728', 'Emprestado temporariamente para outro setor.', 19, 0),
('Sofá 537', 'Equipamento em bom estado de conservação.', '19339', 'Localizado no escritório principal.', 22, 0),
('Notebook 554', 'Novo, ainda em período de garantia.', '83261', 'Etiqueta de patrimônio visível.', 17, 0),
('Caixa de Som 744', 'Apresenta sinais de desgaste, mas funcional.', '28329', 'Utilizado pela equipe administrativa.', 19, 0),
('Armário 720', 'Novo, ainda em período de garantia.', '53321', 'Alocado no setor de TI.', 18, 0),
('Câmera 665', 'Precisa de substituição em breve.', '16390', 'Inventariado no último balanço patrimonial.', 23, 0),
('Projetor 789', 'Em ótimo estado, pouco utilizado.', '87689', 'Inventariado no último balanço patrimonial.', 17, 0),
('Televisão 953', 'Equipamento em bom estado de conservação.', '69383', 'Disponível na sala de reuniões.', 18, 0),
('Estante 988', 'Item essencial para o funcionamento do setor.', '46872', 'Disponível na sala de reuniões.', 17, 1),
('Estante 998', 'Apresenta sinais de desgaste, mas funcional.', '16483', 'Localizado no escritório principal.', 19, 0),
('Ventilador 113', 'Item adquirido recentemente para uso administrativo.', '26871', 'Utilizado pela equipe administrativa.', 20, 1),
('Armário 277', 'Em ótimo estado, pouco utilizado.', '95464', 'Utilizado pela equipe administrativa.', 21, 0),
('Computador 84', 'Precisa de substituição em breve.', '89037', 'Sob responsabilidade do setor de manutenção.', 17, 0),
('Cafeteira 886', 'Novo, ainda em período de garantia.', '17182', 'Requer atualização no sistema de controle.', 19, 1),
('Notebook 300', 'Apresenta sinais de desgaste, mas funcional.', '98231', 'Pertence ao almoxarifado central.', 21, 1),
('Impressora 274', 'Necessita de manutenção preventiva.', '23990', 'Localizado no escritório principal.', 17, 0),
('Micro-ondas 205', 'Precisa de substituição em breve.', '31280', 'Emprestado temporariamente para outro setor.', 19, 0),
('Projetor 392', 'Novo, ainda em período de garantia.', '38434', 'Requer atualização no sistema de controle.', 22, 0),
('Micro-ondas 690', 'Apresenta sinais de desgaste, mas funcional.', '70681', 'Utilizado pela equipe administrativa.', 23, 0),
('Computador 564', 'Item essencial para o funcionamento do setor.', '62871', 'Localizado no escritório principal.', 21, 0),
('Notebook 41', 'Produto antigo, porém em funcionamento.', '37590', 'Disponível na sala de reuniões.', 20, 1),
('Micro-ondas 809', 'Item essencial para o funcionamento do setor.', '62965', 'Pertence ao almoxarifado central.', 19, 0),
('Impressora 85', 'Apresenta sinais de desgaste, mas funcional.', '71072', 'Disponível na sala de reuniões.', 22, 0),
('Cadeira 977', 'Produto antigo, porém em funcionamento.', '80045', 'Disponível na sala de reuniões.', 18, 1),
('Impressora 271', 'Utilizado em treinamentos e reuniões.', '59150', 'Utilizado pela equipe administrativa.', 23, 1),
('Televisão 796', 'Necessita de manutenção preventiva.', '83080', 'Inventariado no último balanço patrimonial.', 18, 1),
('Ventilador 748', 'Item essencial para o funcionamento do setor.', '25050', 'Alocado no setor de TI.', 18, 1),
('Computador 984', 'Em ótimo estado, pouco utilizado.', '86585', 'Etiqueta de patrimônio visível.', 20, 1),
('Telefone 833', 'Produto antigo, porém em funcionamento.', '48291', 'Alocado no setor de TI.', 19, 0),
('Armário 773', 'Utilizado em treinamentos e reuniões.', '67909', 'Disponível na sala de reuniões.', 21, 0),
('Impressora 92', 'Em ótimo estado, pouco utilizado.', '92778', 'Sob responsabilidade do setor de manutenção.', 20, 1),
('Armário 431', 'Equipamento em bom estado de conservação.', '48373', 'Pertence ao almoxarifado central.', 17, 1),
('Computador 187', 'Equipamento em bom estado de conservação.', '72088', 'Sob responsabilidade do setor de manutenção.', 19, 0),
('Aparelho de Som 133', 'Apresenta sinais de desgaste, mas funcional.', '70595', 'Localizado no escritório principal.', 23, 1),
('Armário 854', 'Apresenta sinais de desgaste, mas funcional.', '99698', 'Requer atualização no sistema de controle.', 17, 1),
('Monitor 386', 'Precisa de substituição em breve.', '37327', 'Etiqueta de patrimônio visível.', 23, 1),
('Projetor 957', 'Utilizado em treinamentos e reuniões.', '52783', 'Disponível na sala de reuniões.', 17, 1),
('Projetor 991', 'Utilizado em treinamentos e reuniões.', '48622', 'Pertence ao almoxarifado central.', 21, 0),
('Sofá 404', 'Utilizado em treinamentos e reuniões.', '39349', 'Localizado no escritório principal.', 18, 1),
('Computador 611', 'Precisa de substituição em breve.', '20069', 'Sob responsabilidade do setor de manutenção.', 21, 0),
('Monitor 74', 'Produto antigo, porém em funcionamento.', '36040', 'Alocado no setor de TI.', 21, 0),
('Cafeteira 620', 'Equipamento em bom estado de conservação.', '50791', 'Inventariado no último balanço patrimonial.', 23, 0),
('Câmera 866', 'Precisa de substituição em breve.', '25434', 'Etiqueta de patrimônio visível.', 19, 1),
('Aparelho de Som 402', 'Equipamento em bom estado de conservação.', '56581', 'Disponível na sala de reuniões.', 19, 1),
('Caixa de Som 520', 'Precisa de substituição em breve.', '10756', 'Inventariado no último balanço patrimonial.', 22, 1),
('Ventilador 146', 'Necessita de manutenção preventiva.', '71127', 'Localizado no escritório principal.', 20, 0),
('Televisão 605', 'Equipamento em bom estado de conservação.', '35247', 'Inventariado no último balanço patrimonial.', 20, 1),
('Armário 934', 'Produto antigo, porém em funcionamento.', '56423', 'Etiqueta de patrimônio visível.', 17, 0),
('Impressora 835', 'Apresenta sinais de desgaste, mas funcional.', '51092', 'Etiqueta de patrimônio visível.', 22, 0),
('Monitor 144', 'Precisa de substituição em breve.', '64078', 'Sob responsabilidade do setor de manutenção.', 17, 1),
('Cadeira 11', 'Apresenta sinais de desgaste, mas funcional.', '84290', 'Pertence ao almoxarifado central.', 22, 1),
('Aparelho de Som 18', 'Produto antigo, porém em funcionamento.', '27632', 'Disponível na sala de reuniões.', 17, 0),
('Estante 693', 'Produto antigo, porém em funcionamento.', '71313', 'Etiqueta de patrimônio visível.', 18, 0),
('Cadeira 284', 'Item essencial para o funcionamento do setor.', '22165', 'Emprestado temporariamente para outro setor.', 23, 0),
('Cadeira 239', 'Precisa de substituição em breve.', '53299', 'Etiqueta de patrimônio visível.', 21, 0),
('Aparelho de Som 101', 'Novo, ainda em período de garantia.', '57142', 'Disponível na sala de reuniões.', 20, 1),
('Mesa 431', 'Produto antigo, porém em funcionamento.', '51869', 'Utilizado pela equipe administrativa.', 20, 0),
('Estante 573', 'Item essencial para o funcionamento do setor.', '40545', 'Pertence ao almoxarifado central.', 21, 1),
('Aparelho de Som 304', 'Necessita de manutenção preventiva.', '44925', 'Requer atualização no sistema de controle.', 22, 0),
('Cadeira 430', 'Utilizado em treinamentos e reuniões.', '37715', 'Etiqueta de patrimônio visível.', 18, 0),
('Estante 116', 'Apresenta sinais de desgaste, mas funcional.', '20248', 'Sob responsabilidade do setor de manutenção.', 22, 1),
('Câmera 302', 'Utilizado em treinamentos e reuniões.', '34558', 'Disponível na sala de reuniões.', 23, 1),
('Caixa de Som 138', 'Em ótimo estado, pouco utilizado.', '42363', 'Pertence ao almoxarifado central.', 21, 1),
('Mesa 199', 'Necessita de manutenção preventiva.', '99245', 'Inventariado no último balanço patrimonial.', 17, 0),
('Cadeira 553', 'Item essencial para o funcionamento do setor.', '82750', 'Localizado no escritório principal.', 22, 0),
('Armário 39', 'Equipamento em bom estado de conservação.', '95629', 'Disponível na sala de reuniões.', 19, 1),
('Cadeira 428', 'Produto antigo, porém em funcionamento.', '93437', 'Inventariado no último balanço patrimonial.', 22, 0),
('Estante 901', 'Em ótimo estado, pouco utilizado.', '80867', 'Sob responsabilidade do setor de manutenção.', 19, 0),
('Telefone 733', 'Apresenta sinais de desgaste, mas funcional.', '35829', 'Pertence ao almoxarifado central.', 21, 0),
('Cadeira 613', 'Item adquirido recentemente para uso administrativo.', '11225', 'Disponível na sala de reuniões.', 21, 0),
('Geladeira 711', 'Necessita de manutenção preventiva.', '56708', 'Utilizado pela equipe administrativa.', 18, 1),
('Cafeteira 23', 'Precisa de substituição em breve.', '31738', 'Localizado no escritório principal.', 21, 0),
('Cafeteira 784', 'Em ótimo estado, pouco utilizado.', '94954', 'Utilizado pela equipe administrativa.', 17, 1),
('Mesa 446', 'Item essencial para o funcionamento do setor.', '12390', 'Alocado no setor de TI.', 20, 1),
('Impressora 15', 'Item essencial para o funcionamento do setor.', '78738', 'Emprestado temporariamente para outro setor.', 18, 1),
('Projetor 649', 'Apresenta sinais de desgaste, mas funcional.', '46300', 'Emprestado temporariamente para outro setor.', 20, 0),
('Aparelho de Som 671', 'Novo, ainda em período de garantia.', '86408', 'Alocado no setor de TI.', 21, 0),
('Aparelho de Som 371', 'Apresenta sinais de desgaste, mas funcional.', '68853', 'Etiqueta de patrimônio visível.', 23, 0),
('Mesa 190', 'Produto antigo, porém em funcionamento.', '67448', 'Pertence ao almoxarifado central.', 22, 1),
('Projetor 344', 'Item adquirido recentemente para uso administrativo.', '45744', 'Inventariado no último balanço patrimonial.', 18, 1),
('Aparelho de Som 130', 'Produto antigo, porém em funcionamento.', '40064', 'Inventariado no último balanço patrimonial.', 20, 1),
('Monitor 673', 'Item adquirido recentemente para uso administrativo.', '22743', 'Emprestado temporariamente para outro setor.', 21, 0),
('Armário 949', 'Necessita de manutenção preventiva.', '51601', 'Utilizado pela equipe administrativa.', 18, 1),
('Sofá 168', 'Precisa de substituição em breve.', '22145', 'Utilizado pela equipe administrativa.', 17, 0),
('Notebook 144', 'Item essencial para o funcionamento do setor.', '31941', 'Localizado no escritório principal.', 23, 1),
('Notebook 315', 'Item essencial para o funcionamento do setor.', '45981', 'Requer atualização no sistema de controle.', 20, 0),
('Monitor 514', 'Novo, ainda em período de garantia.', '59312', 'Disponível na sala de reuniões.', 17, 1),
('Televisão 233', 'Item essencial para o funcionamento do setor.', '83289', 'Requer atualização no sistema de controle.', 18, 0),
('Notebook 808', 'Equipamento em bom estado de conservação.', '25697', 'Inventariado no último balanço patrimonial.', 22, 1),
('Armário 161', 'Item essencial para o funcionamento do setor.', '22345', 'Sob responsabilidade do setor de manutenção.', 22, 1);